/**
 * Seed script — Maritime Offshore Oil and Gas Award 2020 [MA000086]
 * Pay rates effective 1 July 2025 (following 2025 Annual Wage Review)
 * Rates sourced from FWC MAPD API.
 *
 * Run after migrate.js: node scripts/seed_ma000086.js
 */
require('dotenv').config();
const pool = require('../src/db/pool');

const AWARD_CODE = 'MA000086';
const EFFECTIVE_DATE = '2025-07-01';

async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // ── Award metadata ────────────────────────────────────────────────────────
    await client.query(`
      INSERT INTO award_metadata (award_code, award_name, effective_date, source_url)
      VALUES ($1, $2, $3, $4)
      ON CONFLICT (award_code) DO UPDATE SET
        award_name = EXCLUDED.award_name,
        effective_date = EXCLUDED.effective_date,
        updated_at = NOW()
    `, [
      AWARD_CODE,
      'Maritime Offshore Oil and Gas Award 2020',
      EFFECTIVE_DATE,
      'https://www.fairwork.gov.au/employment-conditions/awards/awards-summary/ma000086-summary',
    ]);

    // ── Classifications ───────────────────────────────────────────────────────
    const classifications = [
      {
        level: 1, stream: 'facilities',
        title: 'Caterer',
        description: 'Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 10,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Caterer',
        description: 'Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 20,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Caterer',
        description: 'Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 30,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Cook',
        description: 'Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 40,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Cook',
        description: 'Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 50,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Cook',
        description: 'Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 60,
      },
      {
        level: 1, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Integrated Rating',
        description: 'Division 1—64 metres or less - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 70,
      },
      {
        level: 1, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Integrated Rating',
        description: 'Division 1—64 metres or less - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 80,
      },
      {
        level: 1, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Integrated Rating',
        description: 'Division 1—64 metres or less - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 90,
      },
      {
        level: 1, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Integrated Rating',
        description: 'Division 2—more than 64 metres - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 100,
      },
      {
        level: 1, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Integrated Rating',
        description: 'Division 2—more than 64 metres - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 110,
      },
      {
        level: 1, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Integrated Rating',
        description: 'Division 2—more than 64 metres - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 120,
      },
      {
        level: 1, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Provisional IR—under 18 years',
        description: 'Drill ships—Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 130,
      },
      {
        level: 1, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Provisional IR—under 18 years',
        description: 'Drill ships—Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 140,
      },
      {
        level: 1, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Provisional IR—under 18 years',
        description: 'Drill ships—Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 150,
      },
      {
        level: 1, stream: 'non_propelled_modus_under_tow',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 160,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 170,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 180,
      },
      {
        level: 1, stream: 'supply_vessels',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 190,
      },
      {
        level: 1, stream: 'facilities',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 200,
      },
      {
        level: 1, stream: 'general',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 210,
      },
      {
        level: 1, stream: 'stand_by_utility_vessels',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 220,
      },
      {
        level: 1, stream: 'stand_by_utility_vessels',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 230,
      },
      {
        level: 1, stream: 'non_propelled_modus_under_tow',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 240,
      },
      {
        level: 1, stream: 'stand_by_utility_vessels',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 250,
      },
      {
        level: 1, stream: 'supply_vessels',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 260,
      },
      {
        level: 1, stream: 'supply_vessels',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 270,
      },
      {
        level: 1, stream: 'non_propelled_modus_under_tow',
        title: 'Integrated Rating',
        description: 'Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 280,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Deckhand/Integrated Rating',
        description: 'Mary Anne tide or equivalent—Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 290,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Deckhand/Integrated Rating',
        description: 'Mary Anne tide or equivalent—Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 300,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Deckhand/Integrated Rating',
        description: 'Mary Anne tide or equivalent—Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 310,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Deckhand/Integrated Rating',
        description: 'Mooring assistant/utility vessels - Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 320,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Deckhand/Integrated Rating',
        description: 'Mooring assistant/utility vessels - Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 330,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Deckhand/Integrated Rating',
        description: 'Mooring assistant/utility vessels - Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 340,
      },
      {
        level: 1, stream: 'seismic_survey_vessels',
        title: 'Provisional IR—under 18 years',
        description: 'Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 350,
      },
      {
        level: 1, stream: 'seismic_survey_vessels',
        title: 'Provisional IR—under 18 years',
        description: 'Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 360,
      },
      {
        level: 1, stream: 'seismic_survey_vessels',
        title: 'Provisional IR—under 18 years',
        description: 'Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 370,
      },
      {
        level: 1, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Provisional IR—under 18 years',
        description: 'Semi-submersible - Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 380,
      },
      {
        level: 1, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Provisional IR—under 18 years',
        description: 'Semi-submersible - Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 390,
      },
      {
        level: 1, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Provisional IR—under 18 years',
        description: 'Semi-submersible - Provisional IR—under 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 400,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Deckhand/Integrated Rating',
        description: 'Utility vessels including landing barges—Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 410,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Deckhand/Integrated Rating',
        description: 'Utility vessels including landing barges—Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 420,
      },
      {
        level: 1, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Deckhand/Integrated Rating',
        description: 'Utility vessels including landing barges—Deckhand/Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 430,
      },
      {
        level: 2, stream: 'facilities',
        title: 'Deck/Communication Officer',
        description: 'Deck/Communication Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 440,
      },
      {
        level: 2, stream: 'facilities',
        title: 'Deck/Communication Officer',
        description: 'Deck/Communication Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 450,
      },
      {
        level: 2, stream: 'facilities',
        title: 'Deck/Communication Officer',
        description: 'Deck/Communication Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 460,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Second Engineer',
        description: 'Division 1—64 metres or less - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 470,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Second Engineer',
        description: 'Division 1—64 metres or less - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 480,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Second Engineer',
        description: 'Division 1—64 metres or less - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 490,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Second Mate',
        description: 'Division 1—64 metres or less - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 500,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Second Mate',
        description: 'Division 1—64 metres or less - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 510,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Second Engineer',
        description: 'Division 2—more than 64 metres - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 520,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Second Engineer',
        description: 'Division 2—more than 64 metres - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 530,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Second Engineer',
        description: 'Division 2—more than 64 metres - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 540,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Second Mate',
        description: 'Division 2—more than 64 metres - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 550,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Second Mate',
        description: 'Division 2—more than 64 metres - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 560,
      },
      {
        level: 2, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Second Mate',
        description: 'Division 2—more than 64 metres - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 570,
      },
      {
        level: 2, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Provisional IR—over 18 years',
        description: 'Drill ships—Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 580,
      },
      {
        level: 2, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Provisional IR—over 18 years',
        description: 'Drill ships—Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 590,
      },
      {
        level: 2, stream: 'stand_by_utility_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 600,
      },
      {
        level: 2, stream: 'stand_by_utility_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 610,
      },
      {
        level: 2, stream: 'stand_by_utility_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 620,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Mate',
        description: 'Mary Anne tide or equivalent—Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 630,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Mate',
        description: 'Mary Anne tide or equivalent—Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 640,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Mate',
        description: 'Mary Anne tide or equivalent—Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 650,
      },
      {
        level: 2, stream: 'non_propelled_modus_under_tow',
        title: 'Mate',
        description: 'Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 660,
      },
      {
        level: 2, stream: 'non_propelled_modus_under_tow',
        title: 'Mate',
        description: 'Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 670,
      },
      {
        level: 2, stream: 'non_propelled_modus_under_tow',
        title: 'Mate',
        description: 'Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 680,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Chief Engineer',
        description: 'Mooring assistant/utility vessels - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 690,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Chief Engineer',
        description: 'Mooring assistant/utility vessels - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 700,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Chief Engineer',
        description: 'Mooring assistant/utility vessels - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 710,
      },
      {
        level: 2, stream: 'seismic_survey_vessels',
        title: 'Provisional IR—over 18 years',
        description: 'Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 720,
      },
      {
        level: 2, stream: 'seismic_survey_vessels',
        title: 'Provisional IR—over 18 years',
        description: 'Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 730,
      },
      {
        level: 2, stream: 'seismic_survey_vessels',
        title: 'Provisional IR—over 18 years',
        description: 'Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 740,
      },
      {
        level: 2, stream: 'supply_vessels',
        title: 'Second Mate/Second Engineer',
        description: 'Second Mate/Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 750,
      },
      {
        level: 2, stream: 'supply_vessels',
        title: 'Second Mate/Second Engineer',
        description: 'Second Mate/Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 760,
      },
      {
        level: 2, stream: 'supply_vessels',
        title: 'Second Mate/Second Engineer',
        description: 'Second Mate/Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 770,
      },
      {
        level: 2, stream: 'facilities',
        title: 'Second Officer',
        description: 'Second Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 780,
      },
      {
        level: 2, stream: 'facilities',
        title: 'Second Officer',
        description: 'Second Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 790,
      },
      {
        level: 2, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Provisional IR—over 18 years',
        description: 'Semi-submersible - Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 800,
      },
      {
        level: 2, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Provisional IR—over 18 years',
        description: 'Semi-submersible - Provisional IR—over 18 years',
        duties: [],
        indicative_tasks: [],
        sort_order: 810,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Mate',
        description: 'Utility vessels including landing barges—Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 820,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Mate',
        description: 'Utility vessels including landing barges—Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 830,
      },
      {
        level: 2, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Mate',
        description: 'Utility vessels including landing barges—Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 840,
      },
      {
        level: 3, stream: 'seismic_survey_vessels',
        title: 'Caterer Cook',
        description: 'Caterer Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 850,
      },
      {
        level: 3, stream: 'seismic_survey_vessels',
        title: 'Caterer Cook',
        description: 'Caterer Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 860,
      },
      {
        level: 3, stream: 'seismic_survey_vessels',
        title: 'Caterer Cook',
        description: 'Caterer Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 870,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Caterer',
        description: 'Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 880,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Caterer',
        description: 'Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 890,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Caterer',
        description: 'Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 900,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Cook',
        description: 'Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 910,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Cook',
        description: 'Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 920,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Cook',
        description: 'Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 930,
      },
      {
        level: 3, stream: 'stand_by_utility_vessels',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 940,
      },
      {
        level: 3, stream: 'stand_by_utility_vessels',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 950,
      },
      {
        level: 3, stream: 'stand_by_utility_vessels',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 960,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Integrated Rating',
        description: 'Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 970,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Integrated Rating',
        description: 'Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 980,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Integrated Rating',
        description: 'Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 990,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Steward',
        description: 'Chief Steward',
        duties: [],
        indicative_tasks: [],
        sort_order: 1000,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Steward',
        description: 'Chief Steward',
        duties: [],
        indicative_tasks: [],
        sort_order: 1010,
      },
      {
        level: 3, stream: 'facilities',
        title: 'Chief Steward',
        description: 'Chief Steward',
        duties: [],
        indicative_tasks: [],
        sort_order: 1020,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - First Engineer',
        description: 'Division 1—64 metres or less - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1030,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - First Engineer',
        description: 'Division 1—64 metres or less - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1040,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - First Engineer',
        description: 'Division 1—64 metres or less - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1050,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - First Mate',
        description: 'Division 1—64 metres or less - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1060,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - First Mate',
        description: 'Division 1—64 metres or less - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1070,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - First Mate',
        description: 'Division 1—64 metres or less - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1080,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - First Engineer',
        description: 'Division 2—more than 64 metres - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1090,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - First Engineer',
        description: 'Division 2—more than 64 metres - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1100,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - First Engineer',
        description: 'Division 2—more than 64 metres - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1110,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - First Mate',
        description: 'Division 2—more than 64 metres - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1120,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - First Mate',
        description: 'Division 2—more than 64 metres - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1130,
      },
      {
        level: 3, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - First Mate',
        description: 'Division 2—more than 64 metres - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1140,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Caterer',
        description: 'Drill ships—Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1150,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Caterer',
        description: 'Drill ships—Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1160,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Caterer',
        description: 'Drill ships—Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1170,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Integrated Rating',
        description: 'Drill ships—Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1180,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Integrated Rating',
        description: 'Drill ships—Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1190,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Integrated Rating',
        description: 'Drill ships—Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1200,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Cook',
        description: 'Drill ships—Second Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1210,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Cook',
        description: 'Drill ships—Second Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1220,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Cook',
        description: 'Drill ships—Second Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1230,
      },
      {
        level: 3, stream: 'supply_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1240,
      },
      {
        level: 3, stream: 'supply_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1250,
      },
      {
        level: 3, stream: 'supply_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1260,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Chief Engineer',
        description: 'Mary Anne tide or equivalent—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1270,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Chief Engineer',
        description: 'Mary Anne tide or equivalent—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1280,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Chief Engineer',
        description: 'Mary Anne tide or equivalent—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1290,
      },
      {
        level: 3, stream: 'non_propelled_modus_under_tow',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1300,
      },
      {
        level: 3, stream: 'non_propelled_modus_under_tow',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1310,
      },
      {
        level: 3, stream: 'non_propelled_modus_under_tow',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1320,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Mate',
        description: 'Mooring assistant/utility vessels - Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1330,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Mate',
        description: 'Mooring assistant/utility vessels - Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1340,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Mate',
        description: 'Mooring assistant/utility vessels - Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1350,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Caterer',
        description: 'Semi-submersible - Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1360,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Caterer',
        description: 'Semi-submersible - Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1370,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Caterer',
        description: 'Semi-submersible - Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1380,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Integrated Rating',
        description: 'Semi-submersible - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1390,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Integrated Rating',
        description: 'Semi-submersible - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1400,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Integrated Rating',
        description: 'Semi-submersible - Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1410,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Cook',
        description: 'Semi-submersible - Second Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1420,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Cook',
        description: 'Semi-submersible - Second Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1430,
      },
      {
        level: 3, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Cook',
        description: 'Semi-submersible - Second Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1440,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Chief Engineer',
        description: 'Utility vessels including landing barges—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1450,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Chief Engineer',
        description: 'Utility vessels including landing barges—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1460,
      },
      {
        level: 3, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Chief Engineer',
        description: 'Utility vessels including landing barges—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1470,
      },
      {
        level: 4, stream: 'seismic_survey_vessels',
        title: 'Chief Cook/Chief Caterer',
        description: 'Chief Cook/Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1480,
      },
      {
        level: 4, stream: 'seismic_survey_vessels',
        title: 'Chief Cook/Chief Caterer',
        description: 'Chief Cook/Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1490,
      },
      {
        level: 4, stream: 'seismic_survey_vessels',
        title: 'Chief Cook/Chief Caterer',
        description: 'Chief Cook/Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1500,
      },
      {
        level: 4, stream: 'supply_vessels',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1510,
      },
      {
        level: 4, stream: 'supply_vessels',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1520,
      },
      {
        level: 4, stream: 'supply_vessels',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1530,
      },
      {
        level: 4, stream: 'facilities',
        title: 'Chief Officer',
        description: 'Chief Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1540,
      },
      {
        level: 4, stream: 'facilities',
        title: 'Chief Officer',
        description: 'Chief Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1550,
      },
      {
        level: 4, stream: 'facilities',
        title: 'Chief Officer',
        description: 'Chief Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1560,
      },
      {
        level: 4, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Chief Engineer',
        description: 'Division 1—64 metres or less - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1570,
      },
      {
        level: 4, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Chief Engineer',
        description: 'Division 1—64 metres or less - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1580,
      },
      {
        level: 4, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Chief Engineer',
        description: 'Division 2—more than 64 metres - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1590,
      },
      {
        level: 4, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Chief Engineer',
        description: 'Division 2—more than 64 metres - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1600,
      },
      {
        level: 4, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Bosun’s Mate',
        description: 'Drill ships—Bosun’s Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1610,
      },
      {
        level: 4, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Bosun’s Mate',
        description: 'Drill ships—Bosun’s Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1620,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Master',
        description: 'Mary Anne tide or equivalent—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1630,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Master',
        description: 'Mary Anne tide or equivalent—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1640,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent—Master',
        description: 'Mary Anne tide or equivalent—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1650,
      },
      {
        level: 4, stream: 'stand_by_utility_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1660,
      },
      {
        level: 4, stream: 'stand_by_utility_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1670,
      },
      {
        level: 4, stream: 'stand_by_utility_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1680,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Master',
        description: 'Mooring assistant/utility vessels - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1690,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Master',
        description: 'Mooring assistant/utility vessels - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1700,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels - Master',
        description: 'Mooring assistant/utility vessels - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1710,
      },
      {
        level: 4, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Bosun’s Mate',
        description: 'Semi-submersible - Bosun’s Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1720,
      },
      {
        level: 4, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Bosun’s Mate',
        description: 'Semi-submersible - Bosun’s Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1730,
      },
      {
        level: 4, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Bosun’s Mate',
        description: 'Semi-submersible - Bosun’s Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 1740,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Master',
        description: 'Utility vessels including landing barges—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1750,
      },
      {
        level: 4, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges—Master',
        description: 'Utility vessels including landing barges—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1760,
      },
      {
        level: 5, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Master',
        description: 'Division 1—64 metres or less - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1770,
      },
      {
        level: 5, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Master',
        description: 'Division 1—64 metres or less - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1780,
      },
      {
        level: 5, stream: 'support_vessels',
        title: 'Division 1—64 metres or less - Master',
        description: 'Division 1—64 metres or less - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1790,
      },
      {
        level: 5, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Master',
        description: 'Division 2—more than 64 metres - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1800,
      },
      {
        level: 5, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Master',
        description: 'Division 2—more than 64 metres - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1810,
      },
      {
        level: 5, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres - Master',
        description: 'Division 2—more than 64 metres - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1820,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Bosun/Chief Integrated Rating',
        description: 'Drill ships—Bosun/Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1830,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Bosun/Chief Integrated Rating',
        description: 'Drill ships—Bosun/Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1840,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Bosun/Chief Integrated Rating',
        description: 'Drill ships—Bosun/Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 1850,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Caterer',
        description: 'Drill ships—Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1860,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Caterer',
        description: 'Drill ships—Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1870,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Caterer',
        description: 'Drill ships—Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1880,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Cook',
        description: 'Drill ships—Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1890,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Cook',
        description: 'Drill ships—Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1900,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Cook',
        description: 'Drill ships—Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 1910,
      },
      {
        level: 5, stream: 'facilities',
        title: 'Electrical Engineer',
        description: 'Electrical Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1920,
      },
      {
        level: 5, stream: 'facilities',
        title: 'Electrical Engineer',
        description: 'Electrical Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1930,
      },
      {
        level: 5, stream: 'facilities',
        title: 'Electrical Engineer',
        description: 'Electrical Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 1940,
      },
      {
        level: 5, stream: 'seismic_survey_vessels',
        title: 'Integrated Ratings',
        description: 'Integrated Ratings',
        duties: [],
        indicative_tasks: [],
        sort_order: 1950,
      },
      {
        level: 5, stream: 'seismic_survey_vessels',
        title: 'Integrated Ratings',
        description: 'Integrated Ratings',
        duties: [],
        indicative_tasks: [],
        sort_order: 1960,
      },
      {
        level: 5, stream: 'seismic_survey_vessels',
        title: 'Integrated Ratings',
        description: 'Integrated Ratings',
        duties: [],
        indicative_tasks: [],
        sort_order: 1970,
      },
      {
        level: 5, stream: 'supply_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1980,
      },
      {
        level: 5, stream: 'supply_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 1990,
      },
      {
        level: 5, stream: 'supply_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2000,
      },
      {
        level: 5, stream: 'facilities',
        title: 'Second Engineer',
        description: 'Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2010,
      },
      {
        level: 5, stream: 'facilities',
        title: 'Second Engineer',
        description: 'Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2020,
      },
      {
        level: 5, stream: 'facilities',
        title: 'Second Engineer',
        description: 'Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2030,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Bosun/Chief Integrated Rating',
        description: 'Semi-submersible - Bosun/Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 2040,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Bosun/Chief Integrated Rating',
        description: 'Semi-submersible - Bosun/Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 2050,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Bosun/Chief Integrated Rating',
        description: 'Semi-submersible - Bosun/Chief Integrated Rating',
        duties: [],
        indicative_tasks: [],
        sort_order: 2060,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Caterer',
        description: 'Semi-submersible - Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2070,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Caterer',
        description: 'Semi-submersible - Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2080,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Caterer',
        description: 'Semi-submersible - Chief Caterer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2090,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Cook',
        description: 'Semi-submersible - Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 2100,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Cook',
        description: 'Semi-submersible - Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 2110,
      },
      {
        level: 5, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Cook',
        description: 'Semi-submersible - Chief Cook',
        duties: [],
        indicative_tasks: [],
        sort_order: 2120,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Marine Electrician',
        description: 'Drill ships—Marine Electrician',
        duties: [],
        indicative_tasks: [],
        sort_order: 2130,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Marine Electrician',
        description: 'Drill ships—Marine Electrician',
        duties: [],
        indicative_tasks: [],
        sort_order: 2140,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Marine Electrician',
        description: 'Drill ships—Marine Electrician',
        duties: [],
        indicative_tasks: [],
        sort_order: 2150,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Radio Officer',
        description: 'Drill ships—Radio Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2160,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Radio Officer',
        description: 'Drill ships—Radio Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2170,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Radio Officer',
        description: 'Drill ships—Radio Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2180,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Engineer',
        description: 'Drill ships—Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2190,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Engineer',
        description: 'Drill ships—Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2200,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Engineer',
        description: 'Drill ships—Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2210,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Mate',
        description: 'Drill ships—Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2220,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Mate',
        description: 'Drill ships—Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2230,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Second Mate',
        description: 'Drill ships—Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2240,
      },
      {
        level: 6, stream: 'facilities',
        title: 'First Engineer',
        description: 'First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2250,
      },
      {
        level: 6, stream: 'facilities',
        title: 'First Engineer',
        description: 'First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2260,
      },
      {
        level: 6, stream: 'facilities',
        title: 'First Engineer',
        description: 'First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2270,
      },
      {
        level: 6, stream: 'seismic_survey_vessels',
        title: 'Second Mate/Second Engineer',
        description: 'Second Mate/Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2280,
      },
      {
        level: 6, stream: 'seismic_survey_vessels',
        title: 'Second Mate/Second Engineer',
        description: 'Second Mate/Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2290,
      },
      {
        level: 6, stream: 'seismic_survey_vessels',
        title: 'Second Mate/Second Engineer',
        description: 'Second Mate/Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2300,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Marine Electrician',
        description: 'Semi-submersible - Marine Electrician',
        duties: [],
        indicative_tasks: [],
        sort_order: 2310,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Marine Electrician',
        description: 'Semi-submersible - Marine Electrician',
        duties: [],
        indicative_tasks: [],
        sort_order: 2320,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Marine Electrician',
        description: 'Semi-submersible - Marine Electrician',
        duties: [],
        indicative_tasks: [],
        sort_order: 2330,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Radio Officer',
        description: 'Semi-submersible - Radio Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2340,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Radio Officer',
        description: 'Semi-submersible - Radio Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2350,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Radio Officer',
        description: 'Semi-submersible - Radio Officer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2360,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Engineer',
        description: 'Semi-submersible - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2370,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Engineer',
        description: 'Semi-submersible - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2380,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Engineer',
        description: 'Semi-submersible - Second Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2390,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Mate',
        description: 'Semi-submersible - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2400,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Mate',
        description: 'Semi-submersible - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2410,
      },
      {
        level: 6, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Second Mate',
        description: 'Semi-submersible - Second Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2420,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—First Engineer',
        description: 'Drill ships—First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2430,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—First Engineer',
        description: 'Drill ships—First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2440,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—First Engineer',
        description: 'Drill ships—First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2450,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—First Mate',
        description: 'Drill ships—First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2460,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—First Mate',
        description: 'Drill ships—First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2470,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—First Mate',
        description: 'Drill ships—First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2480,
      },
      {
        level: 7, stream: 'facilities',
        title: 'Facility Master',
        description: 'Facility Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2490,
      },
      {
        level: 7, stream: 'facilities',
        title: 'Facility Master',
        description: 'Facility Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2500,
      },
      {
        level: 7, stream: 'facilities',
        title: 'Facility Master',
        description: 'Facility Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2510,
      },
      {
        level: 7, stream: 'seismic_survey_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2520,
      },
      {
        level: 7, stream: 'seismic_survey_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2530,
      },
      {
        level: 7, stream: 'seismic_survey_vessels',
        title: 'First Mate/First Engineer',
        description: 'First Mate/First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2540,
      },
      {
        level: 7, stream: 'facilities',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2550,
      },
      {
        level: 7, stream: 'facilities',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2560,
      },
      {
        level: 7, stream: 'facilities',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2570,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - First Engineer',
        description: 'Semi-submersible - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2580,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - First Engineer',
        description: 'Semi-submersible - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2590,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - First Engineer',
        description: 'Semi-submersible - First Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2600,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - First Mate',
        description: 'Semi-submersible - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2610,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - First Mate',
        description: 'Semi-submersible - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2620,
      },
      {
        level: 7, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - First Mate',
        description: 'Semi-submersible - First Mate',
        duties: [],
        indicative_tasks: [],
        sort_order: 2630,
      },
      {
        level: 8, stream: 'facilities',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2640,
      },
      {
        level: 8, stream: 'facilities',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2650,
      },
      {
        level: 8, stream: 'facilities',
        title: 'Chief Engineer',
        description: 'Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2660,
      },
      {
        level: 8, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Engineer',
        description: 'Drill ships—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2670,
      },
      {
        level: 8, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Chief Engineer',
        description: 'Drill ships—Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2680,
      },
      {
        level: 8, stream: 'seismic_survey_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2690,
      },
      {
        level: 8, stream: 'seismic_survey_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2700,
      },
      {
        level: 8, stream: 'seismic_survey_vessels',
        title: 'Master',
        description: 'Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2710,
      },
      {
        level: 8, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Engineer',
        description: 'Semi-submersible - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2720,
      },
      {
        level: 8, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Chief Engineer',
        description: 'Semi-submersible - Chief Engineer',
        duties: [],
        indicative_tasks: [],
        sort_order: 2730,
      },
      {
        level: 9, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Master',
        description: 'Drill ships—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2740,
      },
      {
        level: 9, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Master',
        description: 'Drill ships—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2750,
      },
      {
        level: 9, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships—Master',
        description: 'Drill ships—Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2760,
      },
      {
        level: 9, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Master',
        description: 'Semi-submersible - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2770,
      },
      {
        level: 9, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Master',
        description: 'Semi-submersible - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2780,
      },
      {
        level: 9, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible - Master',
        description: 'Semi-submersible - Master',
        duties: [],
        indicative_tasks: [],
        sort_order: 2790,
      },
      {
        level: 280, stream: 'support_vessels',
        title: 'Division 1—64 metres or less',
        description: 'Division 1—64 metres or less',
        duties: [],
        indicative_tasks: [],
        sort_order: 2800,
      },
      {
        level: 281, stream: 'support_vessels',
        title: 'Division 1—64 metres or less',
        description: 'Division 1—64 metres or less',
        duties: [],
        indicative_tasks: [],
        sort_order: 2810,
      },
      {
        level: 282, stream: 'support_vessels',
        title: 'Division 1—64 metres or less',
        description: 'Division 1—64 metres or less',
        duties: [],
        indicative_tasks: [],
        sort_order: 2820,
      },
      {
        level: 283, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres',
        description: 'Division 2—more than 64 metres',
        duties: [],
        indicative_tasks: [],
        sort_order: 2830,
      },
      {
        level: 284, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres',
        description: 'Division 2—more than 64 metres',
        duties: [],
        indicative_tasks: [],
        sort_order: 2840,
      },
      {
        level: 285, stream: 'support_vessels',
        title: 'Division 2—more than 64 metres',
        description: 'Division 2—more than 64 metres',
        duties: [],
        indicative_tasks: [],
        sort_order: 2850,
      },
      {
        level: 286, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships',
        description: 'Drill ships',
        duties: [],
        indicative_tasks: [],
        sort_order: 2860,
      },
      {
        level: 287, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships',
        description: 'Drill ships',
        duties: [],
        indicative_tasks: [],
        sort_order: 2870,
      },
      {
        level: 288, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Drill ships',
        description: 'Drill ships',
        duties: [],
        indicative_tasks: [],
        sort_order: 2880,
      },
      {
        level: 289, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent',
        description: 'Mary Anne tide or equivalent',
        duties: [],
        indicative_tasks: [],
        sort_order: 2890,
      },
      {
        level: 290, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent',
        description: 'Mary Anne tide or equivalent',
        duties: [],
        indicative_tasks: [],
        sort_order: 2900,
      },
      {
        level: 291, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mary Anne tide or equivalent',
        description: 'Mary Anne tide or equivalent',
        duties: [],
        indicative_tasks: [],
        sort_order: 2910,
      },
      {
        level: 292, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels',
        description: 'Mooring assistant/utility vessels',
        duties: [],
        indicative_tasks: [],
        sort_order: 2920,
      },
      {
        level: 293, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels',
        description: 'Mooring assistant/utility vessels',
        duties: [],
        indicative_tasks: [],
        sort_order: 2930,
      },
      {
        level: 294, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Mooring assistant/utility vessels',
        description: 'Mooring assistant/utility vessels',
        duties: [],
        indicative_tasks: [],
        sort_order: 2940,
      },
      {
        level: 295, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible',
        description: 'Semi-submersible',
        duties: [],
        indicative_tasks: [],
        sort_order: 2950,
      },
      {
        level: 296, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible',
        description: 'Semi-submersible',
        duties: [],
        indicative_tasks: [],
        sort_order: 2960,
      },
      {
        level: 297, stream: 'self_propelled_drilling_vessels_and_thruster_assis',
        title: 'Semi-submersible',
        description: 'Semi-submersible',
        duties: [],
        indicative_tasks: [],
        sort_order: 2970,
      },
      {
        level: 298, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges',
        description: 'Utility vessels including landing barges',
        duties: [],
        indicative_tasks: [],
        sort_order: 2980,
      },
      {
        level: 299, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges',
        description: 'Utility vessels including landing barges',
        duties: [],
        indicative_tasks: [],
        sort_order: 2990,
      },
      {
        level: 300, stream: 'vessels_engaged_in_operations_in_the_north_west_sh',
        title: 'Utility vessels including landing barges',
        description: 'Utility vessels including landing barges',
        duties: [],
        indicative_tasks: [],
        sort_order: 3000,
      },
    ];

    for (const c of classifications) {
      await client.query(`
        INSERT INTO classifications (award_code, level, stream, pay_point, title, description, duties, indicative_tasks, sort_order)
        VALUES ($1, $2, $3, 1, $4, $5, $6, $7, $8)
        ON CONFLICT (award_code, level, stream, pay_point) DO UPDATE SET
          title = EXCLUDED.title,
          description = EXCLUDED.description,
          duties = EXCLUDED.duties,
          indicative_tasks = EXCLUDED.indicative_tasks,
          sort_order = EXCLUDED.sort_order
      `, [
        AWARD_CODE, c.level, c.stream, c.title, c.description,
        JSON.stringify(c.duties), JSON.stringify(c.indicative_tasks), c.sort_order,
      ]);
    }
    console.log(`✓ Inserted ${classifications.length} classifications`);

    // ── Pay rates ─────────────────────────────────────────────────────────────
    const baseRates = {
      '1_general': 29.71,
    };

    const classResult = await client.query(
      'SELECT id, level, stream FROM classifications WHERE award_code = $1',
      [AWARD_CODE]
    );

    for (const cls of classResult.rows) {
      const baseRate = baseRates[`${cls.level}_${cls.stream}`];
      if (!baseRate) continue;

      const casualRate = Math.round(baseRate * 1.25 * 100) / 100;

      for (const empType of ['full_time', 'part_time']) {
        await client.query(`
          INSERT INTO pay_rates (award_code, classification_id, employment_type, rate_type, rate_amount, effective_date)
          VALUES ($1, $2, $3, 'base_hourly', $4, $5)
          ON CONFLICT (award_code, classification_id, employment_type, rate_type, effective_date)
          DO UPDATE SET rate_amount = EXCLUDED.rate_amount
        `, [AWARD_CODE, cls.id, empType, baseRate, EFFECTIVE_DATE]);
      }

      await client.query(`
        INSERT INTO pay_rates (award_code, classification_id, employment_type, rate_type, rate_amount, effective_date)
        VALUES ($1, $2, 'casual', 'base_hourly', $3, $4)
        ON CONFLICT (award_code, classification_id, employment_type, rate_type, effective_date)
        DO UPDATE SET rate_amount = EXCLUDED.rate_amount
      `, [AWARD_CODE, cls.id, casualRate, EFFECTIVE_DATE]);

      await client.query(`
        INSERT INTO pay_rates (award_code, classification_id, employment_type, rate_type, rate_amount, effective_date)
        VALUES ($1, $2, 'casual', 'casual_loading', 0.25, $3)
        ON CONFLICT (award_code, classification_id, employment_type, rate_type, effective_date)
        DO UPDATE SET rate_amount = EXCLUDED.rate_amount
      `, [AWARD_CODE, cls.id, EFFECTIVE_DATE]);
    }
    console.log('✓ Inserted pay rates');

    // ── Penalty rates ─────────────────────────────────────────────────────────
    const penaltyRates = [
      {
        employment_type: 'full_time', day_type: 'weekday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1, addition_per_hour: null,
        description: 'Ordinary weekday — ×1',
      },
      {
        employment_type: 'full_time', day_type: 'saturday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1.5, addition_per_hour: null,
        description: 'Saturday — ×1.5',
      },
      {
        employment_type: 'full_time', day_type: 'sunday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Sunday — ×2',
      },
      {
        employment_type: 'full_time', day_type: 'public_holiday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2.5, addition_per_hour: null,
        description: 'Public holiday — ×2.5',
      },
      {
        employment_type: 'part_time', day_type: 'weekday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1, addition_per_hour: null,
        description: 'Ordinary weekday — ×1',
      },
      {
        employment_type: 'part_time', day_type: 'saturday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1.5, addition_per_hour: null,
        description: 'Saturday — ×1.5',
      },
      {
        employment_type: 'part_time', day_type: 'sunday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Sunday — ×2',
      },
      {
        employment_type: 'part_time', day_type: 'public_holiday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2.5, addition_per_hour: null,
        description: 'Public holiday — ×2.5',
      },
      {
        employment_type: 'casual', day_type: 'weekday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1, addition_per_hour: null,
        description: 'Ordinary weekday — ×1',
      },
      {
        employment_type: 'casual', day_type: 'saturday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1.5, addition_per_hour: null,
        description: 'Saturday — ×1.5',
      },
      {
        employment_type: 'casual', day_type: 'sunday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Sunday — ×2',
      },
      {
        employment_type: 'casual', day_type: 'public_holiday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2.5, addition_per_hour: null,
        description: 'Public holiday — ×2.5',
      },
    ];

    await client.query(`DELETE FROM penalty_rates WHERE award_code = $1`, [AWARD_CODE]);

    for (const r of penaltyRates) {
      await client.query(`
        INSERT INTO penalty_rates
          (award_code, employment_type, day_type, time_band_start, time_band_end, time_band_label, multiplier, addition_per_hour, description, effective_date)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `, [
        AWARD_CODE, r.employment_type, r.day_type,
        r.time_band_start, r.time_band_end, r.time_band_label,
        r.multiplier, r.addition_per_hour || null, r.description, EFFECTIVE_DATE,
      ]);
    }
    console.log(`✓ Inserted ${penaltyRates.length} penalty rate rules`);

    // ── Overtime rates ────────────────────────────────────────────────────────
    const overtimeRates = [
      { employment_type: 'full_time', threshold_hours: 7.6, period: 'daily', multiplier: 1.5, description: 'Full-time daily overtime — first 2 hours over 7.6 (×1.5)' },
      { employment_type: 'full_time', threshold_hours: 9.6, period: 'daily', multiplier: 2.0, description: 'Full-time daily overtime — after 9.6 hours (×2.0)' },
      { employment_type: 'full_time', threshold_hours: 38, period: 'weekly', multiplier: 1.5, description: 'Full-time weekly overtime — first 2 hours over 38 (×1.5)' },
      { employment_type: 'full_time', threshold_hours: 40, period: 'weekly', multiplier: 2.0, description: 'Full-time weekly overtime — after 40 hours (×2.0)' },
      { employment_type: 'part_time', threshold_hours: 7.6, period: 'daily', multiplier: 1.5, description: 'Part-time daily overtime — first 2 hours over 7.6 (×1.5)' },
      { employment_type: 'part_time', threshold_hours: 9.6, period: 'daily', multiplier: 2.0, description: 'Part-time daily overtime — after 9.6 hours (×2.0)' },
      { employment_type: 'part_time', threshold_hours: 38, period: 'weekly', multiplier: 1.5, description: 'Part-time weekly overtime — first 2 hours over 38 (×1.5)' },
      { employment_type: 'part_time', threshold_hours: 40, period: 'weekly', multiplier: 2.0, description: 'Part-time weekly overtime — after 40 hours (×2.0)' },
      { employment_type: 'casual', threshold_hours: 7.6, period: 'daily', multiplier: 1.5, description: 'Casual daily overtime — first 2 hours over 7.6 (×1.5)' },
      { employment_type: 'casual', threshold_hours: 9.6, period: 'daily', multiplier: 2.0, description: 'Casual daily overtime — after 9.6 hours (×2.0)' },
      { employment_type: 'casual', threshold_hours: 38, period: 'weekly', multiplier: 1.5, description: 'Casual weekly overtime — first 2 hours over 38 (×1.5)' },
      { employment_type: 'casual', threshold_hours: 40, period: 'weekly', multiplier: 2.0, description: 'Casual weekly overtime — after 40 hours (×2.0)' },
    ];

    await client.query(`DELETE FROM overtime_rates WHERE award_code = $1`, [AWARD_CODE]);

    for (const r of overtimeRates) {
      await client.query(`
        INSERT INTO overtime_rates (award_code, employment_type, threshold_hours, period, multiplier, description, effective_date)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
      `, [AWARD_CODE, r.employment_type, r.threshold_hours, r.period, r.multiplier, r.description, EFFECTIVE_DATE]);
    }
    console.log(`✓ Inserted ${overtimeRates.length} overtime rules`);

    // ── Allowances ────────────────────────────────────────────────────────────
    const allowances = [
      {
        allowance_type: 'allowance_specific_to_floating_productio',
        name: 'Allowance specific to floating production facilities—Communication',
        description: 'Allowance specific to floating production facilities—Communication',
        trigger_condition: 'As per award conditions',
        amount: 5.64, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'allowances_specific_to_vessels_other_tha',
        name: 'Allowances specific to vessels other than floating production facilities—Hard-lying 2 berth cabin',
        description: 'Allowances specific to vessels other than floating production facilities—Hard-lying 2 berth cabin',
        trigger_condition: 'As per award conditions',
        amount: 59.15, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'allowances_specific_to_vessels_other_tha',
        name: 'Allowances specific to vessels other than floating production facilities—Hard-lying 4 berth cabin',
        description: 'Allowances specific to vessels other than floating production facilities—Hard-lying 4 berth cabin',
        trigger_condition: 'As per award conditions',
        amount: 94.71, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'allowances_specific_to_vessels_other_tha',
        name: 'Allowances specific to vessels other than floating production facilities—Shared accommodation',
        description: 'Allowances specific to vessels other than floating production facilities—Shared accommodation',
        trigger_condition: 'As per award conditions',
        amount: 47.3, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'vehicle_car',
        name: 'Allowances specific to vessels other than floating production facilities—Vessels temporarily engaged in carriage and handling of cargo',
        description: 'Allowances specific to vessels other than floating production facilities—Vessels temporarily engaged in carriage and handling of cargo',
        trigger_condition: 'As per award conditions',
        amount: 62.88, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'vessels_wrecked_or_stranded',
        name: 'Vessels wrecked or stranded',
        description: 'Vessels wrecked or stranded',
        trigger_condition: 'As per award conditions',
        amount: 33.19, amount_type: 'fixed', per_unit: 'per_hour',
      },
    ];

    await client.query(`DELETE FROM allowances WHERE award_code = $1`, [AWARD_CODE]);

    for (const a of allowances) {
      await client.query(`
        INSERT INTO allowances (award_code, allowance_type, name, description, trigger_condition, amount, amount_type, per_unit, effective_date)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (award_code, allowance_type, effective_date) DO UPDATE SET
          name = EXCLUDED.name, description = EXCLUDED.description, amount = EXCLUDED.amount
      `, [AWARD_CODE, a.allowance_type, a.name, a.description, a.trigger_condition, a.amount, a.amount_type, a.per_unit, EFFECTIVE_DATE]);
    }
    console.log(`✓ Inserted ${allowances.length} allowances`);

    // ── Break entitlements ────────────────────────────────────────────────────
    const breaks = [
      {
        employment_type: null,
        shift_hours_min: 4.0, shift_hours_max: null,
        break_type: 'rest', break_duration_min: 10, is_paid: true,
        timing_rule: 'One paid 10-minute rest break per 4 hours worked',
        description: 'For shifts of 4 hours or more, you are entitled to a paid 10-minute rest break.',
      },
      {
        employment_type: null,
        shift_hours_min: 5.0, shift_hours_max: null,
        break_type: 'meal', break_duration_min: 30, is_paid: false,
        timing_rule: 'No later than 5 hours after starting work',
        description: 'If you work more than 5 hours continuously, you must be given an unpaid meal break of at least 30 minutes.',
      },
    ];

    await client.query(`DELETE FROM break_entitlements WHERE award_code = $1`, [AWARD_CODE]);

    for (const b of breaks) {
      await client.query(`
        INSERT INTO break_entitlements
          (award_code, employment_type, shift_hours_min, shift_hours_max, break_type, break_duration_min, is_paid, timing_rule, description)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `, [
        AWARD_CODE, b.employment_type, b.shift_hours_min, b.shift_hours_max,
        b.break_type, b.break_duration_min, b.is_paid, b.timing_rule, b.description,
      ]);
    }
    console.log(`✓ Inserted ${breaks.length} break entitlement rules`);

    // ── Classification questions ───────────────────────────────────────────────
    const questions = [
      {
        award_code: AWARD_CODE,
        question_key: 'a86_stream',
        question_text: 'What area do you work in?',
        help_text: 'Select the stream that best matches your role.',
        question_type: 'single',
        stream: null,
        parent_question_key: null,
        parent_answer_key: null,
        sort_order: 1,
        answers: [
          { answer_key: 'facilities', answer_text: 'Facilities', sort_order: 1 },
          { answer_key: 'support_vessels', answer_text: 'Support Vessels', sort_order: 2 },
          { answer_key: 'self_propelled_drilling_vessels_and_thruster_assis', answer_text: 'Self Propelled Drilling Vessels And Thruster Assis', sort_order: 3 },
          { answer_key: 'non_propelled_modus_under_tow', answer_text: 'Non Propelled Modus Under Tow', sort_order: 4 },
          { answer_key: 'supply_vessels', answer_text: 'Supply Vessels', sort_order: 5 },
          { answer_key: 'general', answer_text: 'General', sort_order: 6 },
          { answer_key: 'stand_by_utility_vessels', answer_text: 'Stand By Utility Vessels', sort_order: 7 },
          { answer_key: 'vessels_engaged_in_operations_in_the_north_west_sh', answer_text: 'Vessels Engaged In Operations In The North West Sh', sort_order: 8 },
          { answer_key: 'seismic_survey_vessels', answer_text: 'Seismic Survey Vessels', sort_order: 9 },
        ],
      },
      {
        award_code: AWARD_CODE,
        question_key: 'a86_level',
        question_text: 'What is your classification level?',
        help_text: 'Select the level that best matches your role and experience.',
        question_type: 'single',
        stream: null,
        parent_question_key: null,
        parent_answer_key: null,
        sort_order: 2,
        answers: [
          { answer_key: 'level_1', answer_text: 'Caterer', sort_order: 1 },
          { answer_key: 'level_2', answer_text: 'Deck/Communication Officer', sort_order: 2 },
          { answer_key: 'level_3', answer_text: 'Caterer Cook', sort_order: 3 },
          { answer_key: 'level_4', answer_text: 'Chief Cook/Chief Caterer', sort_order: 4 },
          { answer_key: 'level_5', answer_text: 'Division 1—64 metres or less - Master', sort_order: 5 },
          { answer_key: 'level_6', answer_text: 'Drill ships—Marine Electrician', sort_order: 6 },
          { answer_key: 'level_7', answer_text: 'Drill ships—First Engineer', sort_order: 7 },
          { answer_key: 'level_8', answer_text: 'Chief Engineer', sort_order: 8 },
          { answer_key: 'level_9', answer_text: 'Drill ships—Master', sort_order: 9 },
          { answer_key: 'level_280', answer_text: 'Division 1—64 metres or less', sort_order: 10 },
          { answer_key: 'level_281', answer_text: 'Division 1—64 metres or less', sort_order: 11 },
          { answer_key: 'level_282', answer_text: 'Division 1—64 metres or less', sort_order: 12 },
          { answer_key: 'level_283', answer_text: 'Division 2—more than 64 metres', sort_order: 13 },
          { answer_key: 'level_284', answer_text: 'Division 2—more than 64 metres', sort_order: 14 },
          { answer_key: 'level_285', answer_text: 'Division 2—more than 64 metres', sort_order: 15 },
          { answer_key: 'level_286', answer_text: 'Drill ships', sort_order: 16 },
          { answer_key: 'level_287', answer_text: 'Drill ships', sort_order: 17 },
          { answer_key: 'level_288', answer_text: 'Drill ships', sort_order: 18 },
          { answer_key: 'level_289', answer_text: 'Mary Anne tide or equivalent', sort_order: 19 },
          { answer_key: 'level_290', answer_text: 'Mary Anne tide or equivalent', sort_order: 20 },
          { answer_key: 'level_291', answer_text: 'Mary Anne tide or equivalent', sort_order: 21 },
          { answer_key: 'level_292', answer_text: 'Mooring assistant/utility vessels', sort_order: 22 },
          { answer_key: 'level_293', answer_text: 'Mooring assistant/utility vessels', sort_order: 23 },
          { answer_key: 'level_294', answer_text: 'Mooring assistant/utility vessels', sort_order: 24 },
          { answer_key: 'level_295', answer_text: 'Semi-submersible', sort_order: 25 },
          { answer_key: 'level_296', answer_text: 'Semi-submersible', sort_order: 26 },
          { answer_key: 'level_297', answer_text: 'Semi-submersible', sort_order: 27 },
          { answer_key: 'level_298', answer_text: 'Utility vessels including landing barges', sort_order: 28 },
          { answer_key: 'level_299', answer_text: 'Utility vessels including landing barges', sort_order: 29 },
          { answer_key: 'level_300', answer_text: 'Utility vessels including landing barges', sort_order: 30 },
        ],
      },
    ];

    for (const q of questions) {
      const qResult = await client.query(`
        INSERT INTO classification_questions
          (award_code, question_key, question_text, help_text, question_type, stream, parent_question_key, parent_answer_key, sort_order)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (question_key) DO UPDATE SET
          award_code = EXCLUDED.award_code,
          question_text = EXCLUDED.question_text,
          help_text = EXCLUDED.help_text,
          parent_question_key = EXCLUDED.parent_question_key,
          parent_answer_key = EXCLUDED.parent_answer_key,
          sort_order = EXCLUDED.sort_order
        RETURNING id
      `, [
        q.award_code, q.question_key, q.question_text, q.help_text,
        q.question_type, q.stream, q.parent_question_key, q.parent_answer_key, q.sort_order,
      ]);

      const questionId = qResult.rows[0].id;
      await client.query('DELETE FROM classification_answers WHERE question_id = $1', [questionId]);
      for (const a of q.answers) {
        await client.query(`
          INSERT INTO classification_answers (question_id, answer_key, answer_text, sort_order)
          VALUES ($1, $2, $3, $4)
        `, [questionId, a.answer_key, a.answer_text, a.sort_order]);
      }
    }
    console.log(`✓ Inserted ${questions.length} classification questions`);

    await client.query('COMMIT');
    console.log('\n✅ MA000086 seed complete');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
