/**
 * Seed script — Timber Industry Award 2020 [MA000071]
 * Pay rates effective 1 July 2025 (following 2025 Annual Wage Review)
 * Rates sourced from FWC MAPD API.
 *
 * Run after migrate.js: node scripts/seed_ma000071.js
 */
require('dotenv').config();
const pool = require('../src/db/pool');

const AWARD_CODE = 'MA000071';
const EFFECTIVE_DATE = '2025-07-01';

async function seed() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // ── Award metadata ────────────────────────────────────────────────────────
    await client.query(`
      INSERT INTO award_metadata (award_code, award_name, effective_date, source_url)
      VALUES ($1, $2, $3, $4)
      ON CONFLICT (award_code) DO UPDATE SET
        award_name = EXCLUDED.award_name,
        effective_date = EXCLUDED.effective_date,
        updated_at = NOW()
    `, [
      AWARD_CODE,
      'Timber Industry Award 2020',
      EFFECTIVE_DATE,
      'https://www.fairwork.gov.au/employment-conditions/awards/awards-summary/ma000071-summary',
    ]);

    // ── Classifications ───────────────────────────────────────────────────────
    const classifications = [
      {
        level: 1, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: '0–25 cm',
        description: '0–25 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 10,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 20,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 30,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 40,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 50,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 60,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 70,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 80,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'A',
        description: 'A',
        duties: [],
        indicative_tasks: [],
        sort_order: 90,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 100,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 110,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 120,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 130,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 140,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 150,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 160,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 170,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 180,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 190,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 200,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 210,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A1',
        description: 'A1',
        duties: [],
        indicative_tasks: [],
        sort_order: 220,
      },
      {
        level: 1, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'B',
        description: 'B',
        duties: [],
        indicative_tasks: [],
        sort_order: 230,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 240,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 250,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 260,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 270,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 280,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 290,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 300,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 310,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 320,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 330,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 340,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 350,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B1',
        description: 'B1',
        duties: [],
        indicative_tasks: [],
        sort_order: 360,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 370,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 380,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 390,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 400,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 410,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 420,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 430,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 440,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 450,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 460,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 470,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 480,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C1',
        description: 'C1',
        duties: [],
        indicative_tasks: [],
        sort_order: 490,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 500,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 510,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 520,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 530,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 540,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 550,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 560,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 570,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 580,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 590,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 600,
      },
      {
        level: 1, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 610,
      },
      {
        level: 1, stream: 'bass_district_of_tasmania_faller_s',
        title: 'Landing',
        description: 'Landing',
        duties: [],
        indicative_tasks: [],
        sort_order: 620,
      },
      {
        level: 1, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 1',
        description: 'Level 1',
        duties: [],
        indicative_tasks: [],
        sort_order: 630,
      },
      {
        level: 1, stream: 'pulp_and_paper_stream',
        title: 'Level 1',
        description: 'Level 1',
        duties: [],
        indicative_tasks: [],
        sort_order: 640,
      },
      {
        level: 1, stream: 'general_timber_stream',
        title: 'Level 1',
        description: 'Level 1',
        duties: [],
        indicative_tasks: [],
        sort_order: 650,
      },
      {
        level: 1, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 1',
        description: 'Level 1',
        duties: [],
        indicative_tasks: [],
        sort_order: 660,
      },
      {
        level: 2, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: '26–50 cm',
        description: '26–50 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 670,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 680,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 690,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 700,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 710,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 720,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 730,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 740,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 750,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 760,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 770,
      },
      {
        level: 2, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'B',
        description: 'B',
        duties: [],
        indicative_tasks: [],
        sort_order: 780,
      },
      {
        level: 2, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'B',
        description: 'B',
        duties: [],
        indicative_tasks: [],
        sort_order: 790,
      },
      {
        level: 2, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'B',
        description: 'B',
        duties: [],
        indicative_tasks: [],
        sort_order: 800,
      },
      {
        level: 2, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'B',
        description: 'B',
        duties: [],
        indicative_tasks: [],
        sort_order: 810,
      },
      {
        level: 2, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'B',
        description: 'B',
        duties: [],
        indicative_tasks: [],
        sort_order: 820,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 830,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 840,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 850,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 860,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 870,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 880,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 890,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 900,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 910,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 920,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 930,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 940,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B2',
        description: 'B2',
        duties: [],
        indicative_tasks: [],
        sort_order: 950,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 960,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 970,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 980,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 990,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1000,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1010,
      },
      {
        level: 2, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1020,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1030,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1040,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1050,
      },
      {
        level: 2, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C2',
        description: 'C2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1060,
      },
      {
        level: 2, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 2',
        description: 'Level 2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1070,
      },
      {
        level: 2, stream: 'general_timber_stream',
        title: 'Level 2',
        description: 'Level 2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1080,
      },
      {
        level: 2, stream: 'pulp_and_paper_stream',
        title: 'Level 2',
        description: 'Level 2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1090,
      },
      {
        level: 3, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: '51–75 cm',
        description: '51–75 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 1100,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1110,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A2',
        description: 'A2',
        duties: [],
        indicative_tasks: [],
        sort_order: 1120,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1130,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1140,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1150,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1160,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1170,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1180,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1190,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1200,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1210,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1220,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A3',
        description: 'A3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1230,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1240,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1250,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1260,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1270,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1280,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1290,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1300,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1310,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1320,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1330,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1340,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1350,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B3',
        description: 'B3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1360,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1370,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1380,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1390,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1400,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1410,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1420,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1430,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1440,
      },
      {
        level: 3, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'C',
        description: 'C',
        duties: [],
        indicative_tasks: [],
        sort_order: 1450,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1460,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1470,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1480,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1490,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1500,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1510,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1520,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1530,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1540,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1550,
      },
      {
        level: 3, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1560,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1570,
      },
      {
        level: 3, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C3',
        description: 'C3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1580,
      },
      {
        level: 3, stream: 'pulp_and_paper_stream',
        title: 'Level 3',
        description: 'Level 3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1590,
      },
      {
        level: 3, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 3',
        description: 'Level 3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1600,
      },
      {
        level: 3, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 3',
        description: 'Level 3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1610,
      },
      {
        level: 3, stream: 'general_timber_stream',
        title: 'Level 3',
        description: 'Level 3',
        duties: [],
        indicative_tasks: [],
        sort_order: 1620,
      },
      {
        level: 4, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: '76–100 cm',
        description: '76–100 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 1630,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1640,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1650,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1660,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1670,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1680,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1690,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1700,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1710,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1720,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1730,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'A4',
        description: 'A4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1740,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1750,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1760,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1770,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1780,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1790,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1800,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1810,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1820,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1830,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1840,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'B4',
        description: 'B4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1850,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1860,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1870,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1880,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1890,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1900,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1910,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1920,
      },
      {
        level: 4, stream: 'eastern_district_of_tasmania_faller_s_rate_table',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1930,
      },
      {
        level: 4, stream: 'bass_district_of_tasmania_faller_s',
        title: 'C4',
        description: 'C4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1940,
      },
      {
        level: 4, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 4',
        description: 'Level 4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1950,
      },
      {
        level: 4, stream: 'pulp_and_paper_stream',
        title: 'Level 4',
        description: 'Level 4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1960,
      },
      {
        level: 4, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 4',
        description: 'Level 4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1970,
      },
      {
        level: 4, stream: 'general_timber_stream',
        title: 'Level 4',
        description: 'Level 4',
        duties: [],
        indicative_tasks: [],
        sort_order: 1980,
      },
      {
        level: 5, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: '101–150 cm',
        description: '101–150 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 1990,
      },
      {
        level: 5, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 4A',
        description: 'Level 4A',
        duties: [],
        indicative_tasks: [],
        sort_order: 2000,
      },
      {
        level: 5, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 4A',
        description: 'Level 4A',
        duties: [],
        indicative_tasks: [],
        sort_order: 2010,
      },
      {
        level: 5, stream: 'general_timber_stream',
        title: 'Level 5',
        description: 'Level 5',
        duties: [],
        indicative_tasks: [],
        sort_order: 2020,
      },
      {
        level: 5, stream: 'pulp_and_paper_stream',
        title: 'Level 5',
        description: 'Level 5',
        duties: [],
        indicative_tasks: [],
        sort_order: 2030,
      },
      {
        level: 6, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: '151–200 cm',
        description: '151–200 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 2040,
      },
      {
        level: 6, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 5',
        description: 'Level 5',
        duties: [],
        indicative_tasks: [],
        sort_order: 2050,
      },
      {
        level: 6, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 5',
        description: 'Level 5',
        duties: [],
        indicative_tasks: [],
        sort_order: 2060,
      },
      {
        level: 6, stream: 'general_timber_stream',
        title: 'Level 6',
        description: 'Level 6',
        duties: [],
        indicative_tasks: [],
        sort_order: 2070,
      },
      {
        level: 6, stream: 'pulp_and_paper_stream',
        title: 'Level 6',
        description: 'Level 6',
        duties: [],
        indicative_tasks: [],
        sort_order: 2080,
      },
      {
        level: 7, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 6',
        description: 'Level 6',
        duties: [],
        indicative_tasks: [],
        sort_order: 2090,
      },
      {
        level: 7, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 6',
        description: 'Level 6',
        duties: [],
        indicative_tasks: [],
        sort_order: 2100,
      },
      {
        level: 7, stream: 'pulp_and_paper_stream',
        title: 'Level 7',
        description: 'Level 7',
        duties: [],
        indicative_tasks: [],
        sort_order: 2110,
      },
      {
        level: 7, stream: 'general_timber_stream',
        title: 'Level 7',
        description: 'Level 7',
        duties: [],
        indicative_tasks: [],
        sort_order: 2120,
      },
      {
        level: 7, stream: 'cull_falling_rates_in_the_eastern_and_bass_distric',
        title: 'over 200 cm',
        description: 'over 200 cm',
        duties: [],
        indicative_tasks: [],
        sort_order: 2130,
      },
      {
        level: 8, stream: 'wood_and_timber_furniture_stream',
        title: 'Level 7',
        description: 'Level 7',
        duties: [],
        indicative_tasks: [],
        sort_order: 2140,
      },
      {
        level: 8, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'Level 7',
        description: 'Level 7',
        duties: [],
        indicative_tasks: [],
        sort_order: 2150,
      },
      {
        level: 8, stream: 'pulp_and_paper_stream',
        title: 'Level 8',
        description: 'Level 8',
        duties: [],
        indicative_tasks: [],
        sort_order: 2160,
      },
      {
        level: 9, stream: 'pulp_and_paper_stream',
        title: 'Level 9',
        description: 'Level 9',
        duties: [],
        indicative_tasks: [],
        sort_order: 2170,
      },
      {
        level: 218, stream: 'softwood_falling_table_softwood_falling_in_the_eas',
        title: 'Falling',
        description: 'Falling',
        duties: [],
        indicative_tasks: [],
        sort_order: 2180,
      },
      {
        level: 219, stream: 'general_timber_stream',
        title: 'General Timber Stream',
        description: 'General Timber Stream',
        duties: [],
        indicative_tasks: [],
        sort_order: 2190,
      },
      {
        level: 220, stream: 'general_timber_stream_and_wood_and_timber_furnitur',
        title: 'General Timber Stream and Wood and Timber Furniture Stream',
        description: 'General Timber Stream and Wood and Timber Furniture Stream',
        duties: [],
        indicative_tasks: [],
        sort_order: 2200,
      },
      {
        level: 221, stream: 'pulp_and_paper_stream',
        title: 'Pulp and Paper Stream',
        description: 'Pulp and Paper Stream',
        duties: [],
        indicative_tasks: [],
        sort_order: 2210,
      },
      {
        level: 222, stream: 'wood_and_timber_furniture_stream',
        title: 'Wood and Timber Furniture Stream',
        description: 'Wood and Timber Furniture Stream',
        duties: [],
        indicative_tasks: [],
        sort_order: 2220,
      },
    ];

    for (const c of classifications) {
      await client.query(`
        INSERT INTO classifications (award_code, level, stream, pay_point, title, description, duties, indicative_tasks, sort_order)
        VALUES ($1, $2, $3, 1, $4, $5, $6, $7, $8)
        ON CONFLICT (award_code, level, stream, pay_point) DO UPDATE SET
          title = EXCLUDED.title,
          description = EXCLUDED.description,
          duties = EXCLUDED.duties,
          indicative_tasks = EXCLUDED.indicative_tasks,
          sort_order = EXCLUDED.sort_order
      `, [
        AWARD_CODE, c.level, c.stream, c.title, c.description,
        JSON.stringify(c.duties), JSON.stringify(c.indicative_tasks), c.sort_order,
      ]);
    }
    console.log(`✓ Inserted ${classifications.length} classifications`);

    // ── Pay rates ─────────────────────────────────────────────────────────────
    const baseRates = {
      '1_wood_and_timber_furniture_stream': 24.28,
      '1_pulp_and_paper_stream': 25.46,
      '1_general_timber_stream': 24.28,
      '2_wood_and_timber_furniture_stream': 24.95,
      '2_general_timber_stream': 24.95,
      '3_pulp_and_paper_stream': 26.81,
      '3_wood_and_timber_furniture_stream': 25.85,
      '3_general_timber_stream': 25.85,
      '4_pulp_and_paper_stream': 27.32,
      '4_general_timber_stream': 26.7,
      '5_wood_and_timber_furniture_stream': 27.14,
      '5_general_timber_stream': 28.12,
      '5_pulp_and_paper_stream': 28.12,
      '6_wood_and_timber_furniture_stream': 28.12,
      '6_general_timber_stream': 29,
      '6_pulp_and_paper_stream': 29,
      '7_wood_and_timber_furniture_stream': 29,
      '7_pulp_and_paper_stream': 29.88,
      '7_general_timber_stream': 30.68,
      '8_wood_and_timber_furniture_stream': 30.68,
      '8_pulp_and_paper_stream': 30.68,
      '9_pulp_and_paper_stream': 31.56,
    };

    const classResult = await client.query(
      'SELECT id, level, stream FROM classifications WHERE award_code = $1',
      [AWARD_CODE]
    );

    for (const cls of classResult.rows) {
      const baseRate = baseRates[`${cls.level}_${cls.stream}`];
      if (!baseRate) continue;

      const casualRate = Math.round(baseRate * 1.25 * 100) / 100;

      for (const empType of ['full_time', 'part_time']) {
        await client.query(`
          INSERT INTO pay_rates (award_code, classification_id, employment_type, rate_type, rate_amount, effective_date)
          VALUES ($1, $2, $3, 'base_hourly', $4, $5)
          ON CONFLICT (award_code, classification_id, employment_type, rate_type, effective_date)
          DO UPDATE SET rate_amount = EXCLUDED.rate_amount
        `, [AWARD_CODE, cls.id, empType, baseRate, EFFECTIVE_DATE]);
      }

      await client.query(`
        INSERT INTO pay_rates (award_code, classification_id, employment_type, rate_type, rate_amount, effective_date)
        VALUES ($1, $2, 'casual', 'base_hourly', $3, $4)
        ON CONFLICT (award_code, classification_id, employment_type, rate_type, effective_date)
        DO UPDATE SET rate_amount = EXCLUDED.rate_amount
      `, [AWARD_CODE, cls.id, casualRate, EFFECTIVE_DATE]);

      await client.query(`
        INSERT INTO pay_rates (award_code, classification_id, employment_type, rate_type, rate_amount, effective_date)
        VALUES ($1, $2, 'casual', 'casual_loading', 0.25, $3)
        ON CONFLICT (award_code, classification_id, employment_type, rate_type, effective_date)
        DO UPDATE SET rate_amount = EXCLUDED.rate_amount
      `, [AWARD_CODE, cls.id, EFFECTIVE_DATE]);
    }
    console.log('✓ Inserted pay rates');

    // ── Penalty rates ─────────────────────────────────────────────────────────
    const penaltyRates = [
      {
        employment_type: 'full_time', day_type: 'weekday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1, addition_per_hour: null,
        description: 'Ordinary weekday — ×1',
      },
      {
        employment_type: 'full_time', day_type: 'saturday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Monday to Saturday - After 2 hours — Full-time ×2',
      },
      {
        employment_type: 'full_time', day_type: 'sunday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Sunday — Full-time ×2',
      },
      {
        employment_type: 'full_time', day_type: 'public_holiday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2.5, addition_per_hour: null,
        description: 'Public holiday — Full-time ×2.5',
      },
      {
        employment_type: 'part_time', day_type: 'weekday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1, addition_per_hour: null,
        description: 'Ordinary weekday — ×1',
      },
      {
        employment_type: 'part_time', day_type: 'saturday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Monday to Saturday - After 2 hours — Part-time ×2',
      },
      {
        employment_type: 'part_time', day_type: 'sunday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Sunday — Part-time ×2',
      },
      {
        employment_type: 'part_time', day_type: 'public_holiday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2.5, addition_per_hour: null,
        description: 'Public holiday — Part-time ×2.5',
      },
      {
        employment_type: 'casual', day_type: 'weekday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 1, addition_per_hour: null,
        description: 'Ordinary weekday — ×1',
      },
      {
        employment_type: 'casual', day_type: 'saturday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Monday to Saturday - After 2 hours — Casual ×2',
      },
      {
        employment_type: 'casual', day_type: 'sunday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2, addition_per_hour: null,
        description: 'Sunday — Casual ×2',
      },
      {
        employment_type: 'casual', day_type: 'public_holiday',
        time_band_start: null, time_band_end: null, time_band_label: null,
        multiplier: 2.75, addition_per_hour: null,
        description: 'Public Holiday — Casual ×2.75',
      },
    ];

    await client.query(`DELETE FROM penalty_rates WHERE award_code = $1`, [AWARD_CODE]);

    for (const r of penaltyRates) {
      await client.query(`
        INSERT INTO penalty_rates
          (award_code, employment_type, day_type, time_band_start, time_band_end, time_band_label, multiplier, addition_per_hour, description, effective_date)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
      `, [
        AWARD_CODE, r.employment_type, r.day_type,
        r.time_band_start, r.time_band_end, r.time_band_label,
        r.multiplier, r.addition_per_hour || null, r.description, EFFECTIVE_DATE,
      ]);
    }
    console.log(`✓ Inserted ${penaltyRates.length} penalty rate rules`);

    // ── Overtime rates ────────────────────────────────────────────────────────
    const overtimeRates = [
      { employment_type: 'full_time', threshold_hours: 7.6, period: 'daily', multiplier: 1.5, description: 'Full-time daily overtime — first 2 hours over 7.6 (×1.5)' },
      { employment_type: 'full_time', threshold_hours: 9.6, period: 'daily', multiplier: 2.0, description: 'Full-time daily overtime — after 9.6 hours (×2.0)' },
      { employment_type: 'full_time', threshold_hours: 38, period: 'weekly', multiplier: 1.5, description: 'Full-time weekly overtime — first 2 hours over 38 (×1.5)' },
      { employment_type: 'full_time', threshold_hours: 40, period: 'weekly', multiplier: 2.0, description: 'Full-time weekly overtime — after 40 hours (×2.0)' },
      { employment_type: 'part_time', threshold_hours: 7.6, period: 'daily', multiplier: 1.5, description: 'Part-time daily overtime — first 2 hours over 7.6 (×1.5)' },
      { employment_type: 'part_time', threshold_hours: 9.6, period: 'daily', multiplier: 2.0, description: 'Part-time daily overtime — after 9.6 hours (×2.0)' },
      { employment_type: 'part_time', threshold_hours: 38, period: 'weekly', multiplier: 1.5, description: 'Part-time weekly overtime — first 2 hours over 38 (×1.5)' },
      { employment_type: 'part_time', threshold_hours: 40, period: 'weekly', multiplier: 2.0, description: 'Part-time weekly overtime — after 40 hours (×2.0)' },
      { employment_type: 'casual', threshold_hours: 7.6, period: 'daily', multiplier: 1.5, description: 'Casual daily overtime — first 2 hours over 7.6 (×1.5)' },
      { employment_type: 'casual', threshold_hours: 9.6, period: 'daily', multiplier: 2.0, description: 'Casual daily overtime — after 9.6 hours (×2.0)' },
      { employment_type: 'casual', threshold_hours: 38, period: 'weekly', multiplier: 1.5, description: 'Casual weekly overtime — first 2 hours over 38 (×1.5)' },
      { employment_type: 'casual', threshold_hours: 40, period: 'weekly', multiplier: 2.0, description: 'Casual weekly overtime — after 40 hours (×2.0)' },
    ];

    await client.query(`DELETE FROM overtime_rates WHERE award_code = $1`, [AWARD_CODE]);

    for (const r of overtimeRates) {
      await client.query(`
        INSERT INTO overtime_rates (award_code, employment_type, threshold_hours, period, multiplier, description, effective_date)
        VALUES ($1, $2, $3, $4, $5, $6, $7)
      `, [AWARD_CODE, r.employment_type, r.threshold_hours, r.period, r.multiplier, r.description, EFFECTIVE_DATE]);
    }
    console.log(`✓ Inserted ${overtimeRates.length} overtime rules`);

    // ── Allowances ────────────────────────────────────────────────────────────
    const allowances = [
      {
        allowance_type: 'camping_including_firefighters_maximum_p',
        name: 'Camping (including firefighters)—maximum per week—a maximum amount of',
        description: 'Camping (including firefighters)—maximum per week—a maximum amount of',
        trigger_condition: 'As per award conditions',
        amount: 220.16, amount_type: 'weekly', per_unit: 'per_week',
      },
      {
        allowance_type: 'camping_including_firefighters_per_worki',
        name: 'Camping (including firefighters)—per working day',
        description: 'Camping (including firefighters)—per working day',
        trigger_condition: 'As per award conditions',
        amount: 31.45, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'meal',
        name: 'Meal—overtime',
        description: 'Meal—overtime',
        trigger_condition: 'As per award conditions',
        amount: 18.38, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'tool',
        name: 'Tools—furnishing employee—insurance—a maximum amount of',
        description: 'Tools—furnishing employee—insurance—a maximum amount of',
        trigger_condition: 'As per award conditions',
        amount: 868.3, amount_type: 'fixed', per_unit: 'per_shift',
      },
      {
        allowance_type: 'tool',
        name: 'Tools—furnishing employee—tradesperson',
        description: 'Tools—furnishing employee—tradesperson',
        trigger_condition: 'As per award conditions',
        amount: 17.53, amount_type: 'weekly', per_unit: 'per_week',
      },
      {
        allowance_type: 'tool',
        name: 'Tools—millwright',
        description: 'Tools—millwright',
        trigger_condition: 'As per award conditions',
        amount: 5.76, amount_type: 'weekly', per_unit: 'per_week',
      },
    ];

    await client.query(`DELETE FROM allowances WHERE award_code = $1`, [AWARD_CODE]);

    for (const a of allowances) {
      await client.query(`
        INSERT INTO allowances (award_code, allowance_type, name, description, trigger_condition, amount, amount_type, per_unit, effective_date)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (award_code, allowance_type, effective_date) DO UPDATE SET
          name = EXCLUDED.name, description = EXCLUDED.description, amount = EXCLUDED.amount
      `, [AWARD_CODE, a.allowance_type, a.name, a.description, a.trigger_condition, a.amount, a.amount_type, a.per_unit, EFFECTIVE_DATE]);
    }
    console.log(`✓ Inserted ${allowances.length} allowances`);

    // ── Break entitlements ────────────────────────────────────────────────────
    const breaks = [
      {
        employment_type: null,
        shift_hours_min: 4.0, shift_hours_max: null,
        break_type: 'rest', break_duration_min: 10, is_paid: true,
        timing_rule: 'One paid 10-minute rest break per 4 hours worked',
        description: 'For shifts of 4 hours or more, you are entitled to a paid 10-minute rest break.',
      },
      {
        employment_type: null,
        shift_hours_min: 5.0, shift_hours_max: null,
        break_type: 'meal', break_duration_min: 30, is_paid: false,
        timing_rule: 'No later than 5 hours after starting work',
        description: 'If you work more than 5 hours continuously, you must be given an unpaid meal break of at least 30 minutes.',
      },
    ];

    await client.query(`DELETE FROM break_entitlements WHERE award_code = $1`, [AWARD_CODE]);

    for (const b of breaks) {
      await client.query(`
        INSERT INTO break_entitlements
          (award_code, employment_type, shift_hours_min, shift_hours_max, break_type, break_duration_min, is_paid, timing_rule, description)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
      `, [
        AWARD_CODE, b.employment_type, b.shift_hours_min, b.shift_hours_max,
        b.break_type, b.break_duration_min, b.is_paid, b.timing_rule, b.description,
      ]);
    }
    console.log(`✓ Inserted ${breaks.length} break entitlement rules`);

    // ── Classification questions ───────────────────────────────────────────────
    const questions = [
      {
        award_code: AWARD_CODE,
        question_key: 'a71_stream',
        question_text: 'What area do you work in?',
        help_text: 'Select the stream that best matches your role.',
        question_type: 'single',
        stream: null,
        parent_question_key: null,
        parent_answer_key: null,
        sort_order: 1,
        answers: [
          { answer_key: 'cull_falling_rates_in_the_eastern_and_bass_distric', answer_text: 'Cull Falling Rates In The Eastern And Bass Distric', sort_order: 1 },
          { answer_key: 'softwood_falling_table_softwood_falling_in_the_eas', answer_text: 'Softwood Falling Table Softwood Falling In The Eas', sort_order: 2 },
          { answer_key: 'bass_district_of_tasmania_faller_s', answer_text: 'Bass District Of Tasmania Faller S', sort_order: 3 },
          { answer_key: 'eastern_district_of_tasmania_faller_s_rate_table', answer_text: 'Eastern District Of Tasmania Faller S Rate Table', sort_order: 4 },
          { answer_key: 'wood_and_timber_furniture_stream', answer_text: 'Wood And Timber Furniture Stream', sort_order: 5 },
          { answer_key: 'pulp_and_paper_stream', answer_text: 'Pulp And Paper Stream', sort_order: 6 },
          { answer_key: 'general_timber_stream', answer_text: 'General Timber Stream', sort_order: 7 },
          { answer_key: 'general_timber_stream_and_wood_and_timber_furnitur', answer_text: 'General Timber Stream And Wood And Timber Furnitur', sort_order: 8 },
        ],
      },
      {
        award_code: AWARD_CODE,
        question_key: 'a71_level',
        question_text: 'What is your classification level?',
        help_text: 'Select the level that best matches your role and experience.',
        question_type: 'single',
        stream: null,
        parent_question_key: null,
        parent_answer_key: null,
        sort_order: 2,
        answers: [
          { answer_key: 'level_1', answer_text: '0–25 cm', sort_order: 1 },
          { answer_key: 'level_2', answer_text: '26–50 cm', sort_order: 2 },
          { answer_key: 'level_3', answer_text: '51–75 cm', sort_order: 3 },
          { answer_key: 'level_4', answer_text: '76–100 cm', sort_order: 4 },
          { answer_key: 'level_5', answer_text: '101–150 cm', sort_order: 5 },
          { answer_key: 'level_6', answer_text: '151–200 cm', sort_order: 6 },
          { answer_key: 'level_7', answer_text: 'Level 6', sort_order: 7 },
          { answer_key: 'level_8', answer_text: 'Level 7', sort_order: 8 },
          { answer_key: 'level_9', answer_text: 'Level 9', sort_order: 9 },
          { answer_key: 'level_218', answer_text: 'Falling', sort_order: 10 },
          { answer_key: 'level_219', answer_text: 'General Timber Stream', sort_order: 11 },
          { answer_key: 'level_220', answer_text: 'General Timber Stream and Wood and Timber Furniture Stream', sort_order: 12 },
          { answer_key: 'level_221', answer_text: 'Pulp and Paper Stream', sort_order: 13 },
          { answer_key: 'level_222', answer_text: 'Wood and Timber Furniture Stream', sort_order: 14 },
        ],
      },
    ];

    for (const q of questions) {
      const qResult = await client.query(`
        INSERT INTO classification_questions
          (award_code, question_key, question_text, help_text, question_type, stream, parent_question_key, parent_answer_key, sort_order)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
        ON CONFLICT (question_key) DO UPDATE SET
          award_code = EXCLUDED.award_code,
          question_text = EXCLUDED.question_text,
          help_text = EXCLUDED.help_text,
          parent_question_key = EXCLUDED.parent_question_key,
          parent_answer_key = EXCLUDED.parent_answer_key,
          sort_order = EXCLUDED.sort_order
        RETURNING id
      `, [
        q.award_code, q.question_key, q.question_text, q.help_text,
        q.question_type, q.stream, q.parent_question_key, q.parent_answer_key, q.sort_order,
      ]);

      const questionId = qResult.rows[0].id;
      await client.query('DELETE FROM classification_answers WHERE question_id = $1', [questionId]);
      for (const a of q.answers) {
        await client.query(`
          INSERT INTO classification_answers (question_id, answer_key, answer_text, sort_order)
          VALUES ($1, $2, $3, $4)
        `, [questionId, a.answer_key, a.answer_text, a.sort_order]);
      }
    }
    console.log(`✓ Inserted ${questions.length} classification questions`);

    await client.query('COMMIT');
    console.log('\n✅ MA000071 seed complete');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Seed failed:', err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
