/**
 * Build-time rate data provider — reads from pre-extracted seed-data.json.
 *
 * The JSON file is generated by: node scripts/extract-seed-data.js
 * Run that script before building whenever seed files change.
 */

import seedData from './seed-data.json';
import type { AwardRateData, LevelRate, PenaltyInfo, AllowanceInfo } from './award-rates';

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

interface SeedClassification {
  level: number;
  stream: string;
  title: string;
  description: string;
  duties: string[];
  ftRate: number;
}

interface SeedAward {
  awardCode: string;
  effectiveDate: string;
  classifications: SeedClassification[];
  penalties: PenaltyInfo[];
  allowances: AllowanceInfo[];
}

const data = seedData as unknown as Record<string, SeedAward>;

export function getAwardRatesFromSeed(awardCode: string): AwardRateData {
  const award = data[awardCode];
  if (!award) {
    return { awardCode, levels: [], penalties: [], allowances: [], effectiveDate: '1 July 2025', rateType: 'hourly' };
  }

  // Format effective date
  let effectiveDate = '1 July 2025';
  if (award.effectiveDate) {
    const d = new Date(award.effectiveDate);
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    effectiveDate = `${d.getUTCDate()} ${months[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
  }

  // Build penalty lookup
  const ftPenalties = (award.penalties || []).filter(p => !p.timeBandLabel);
  const getFtMult = (day: string) => ftPenalties.find(p => p.dayType === day)?.ftMultiplier ?? 1;
  const getCasMult = (day: string) => ftPenalties.find(p => p.dayType === day)?.casualMultiplier ?? 1;

  // Build level rates from classifications
  const levels: LevelRate[] = [];
  for (const cls of award.classifications) {
    if (!cls.ftRate || cls.ftRate <= 0) continue;

    const ft = cls.ftRate;
    const casual = round2(ft * 1.25);

    levels.push({
      level: cls.level,
      stream: cls.stream,
      title: cls.title,
      ftRate: ft,
      casualRate: casual,
      saturdayFt: round2(ft * getFtMult('saturday')),
      saturdayCasual: round2(casual * getCasMult('saturday')),
      sundayFt: round2(ft * getFtMult('sunday')),
      sundayCasual: round2(casual * getCasMult('sunday')),
      publicHolidayFt: round2(ft * getFtMult('public_holiday')),
      publicHolidayCasual: round2(casual * getCasMult('public_holiday')),
    });
  }

  return {
    awardCode,
    levels,
    penalties: award.penalties || [],
    allowances: award.allowances || [],
    effectiveDate,
    rateType: (award as unknown as Record<string, unknown>).rateType === 'daily' ? 'daily' as const : 'hourly' as const,
  };
}
